inherit_from: .rubocop_todo.yml

AllCops:
  Excludes:
    - db/**
    - config/**
    - script/**
    - spec/**
    - vendor/**

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 120
